name: Validate Lockfiles

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/test-suite/package.json"
      - "apps/test-suite/pnpm-lock.yaml"

jobs:
  validate:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Validate test-suite lockfile
        run: pnpm install --frozen-lockfile
        working-directory: apps/test-suite
